### ISSUE TITLE
Sorting alerts by date.

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#1013]
We need to implement sorting of alerts by date on the backend side in all lists of alerts (all, my, dependent). Because now such sorting is implemented on the FE side and this is buggy. If newest alerts will be on the next pages - user will see it only if he will scroll back to top.

## Useful information
Here are some useful links and information if you are new to this repository and OpenDataDiscovery system

### Documentation
We keep all documentation in our [GitBook](https://docs.opendatadiscovery.org/). It contains all kind of information such as
system overview and use cases (why are we doing this), architecture (how are we doing this), etc.
Please take a look at the `Developer Guides` section where we explain [how to contribute](https://docs.opendatadiscovery.org/developer-guides/how-to-contribute) and
[how to setup local environment](https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform)

### Contact us
If you're struggling with something, please feel free to ask us anything here in the GitHub issue ticket or via our [Slack community](https://go.opendatadiscovery.org/slack).

**Comment by DementevNikita** [comment]
Closing this as done
