### ISSUE TITLE
Add PII classification to existing column in the data set

### ISSUE THREAD

**Issue by sivapadman** [opendatadiscovery/odd-platform#130]
I am trying to add PII classification to the existing column in the data set. The following is the navigation, I followed
1.Clicked on Catalog
2.Clicked on Datasets
3.Typed users on Search
4.Clicked on Users dataset
5.Clicked on Structure
6.Clicked on existing column birth_date to classify as PII, But I could see only Edit Labels option or Edit Description

How do I add PII classification to the existing columns

**Comment by DementevNikita** [comment]
hey @sivapadman, thank you for creating the issue!

Generally, you can use labels to mark columns that are PII. Click `Edit Labels` option, type PII and click `Save`

**Comment by DementevNikita** [comment]
hey @sivapadman!

This feature will be released in 0.2 release coming this week. It contains searching capabilities by dataset field's name, description and labels. So now you could assign PII label to the field and then find it by query "PII"
