### ISSUE TITLE
View materialized views among datasets collected from source database

### ISSUE THREAD

**Issue by OmarBochkati** [opendatadiscovery/odd-platform#1401]
We currently have a postgres database containing data on on top of this data we build some materialized views that we use as DataProducts for reporting and analytics purposes. We are looking for a Data Catalog and we were impressed by ODD but when we started to test it out and configured the odd-collector to harvest the metadata from the source database, but were surprised that none of our materialized views showed up in the list of datasets returned by the collector. Is it a misconfiguration on our end or is this the expected behaviour of the odd-collector ?
Thanks in advance

**Comment by Vixtir** [comment]
Hi @OmarBochkati , materialized views added by new odd-collector release! 
You will need to pull latest [image](https://github.com/opendatadiscovery/odd-collector/pkgs/container/odd-collector)

**Comment by OmarBochkati** [comment]
Hello @Vixtir, Thank you so much for quickly handling this !! Will pull the new image and test it.
Thanks again 🙏
