### ISSUE TITLE
Linked Items (Terms) Not Being Displayed For Columns  

### ISSUE THREAD

**Issue by clintjb** [opendatadiscovery/odd-platform#1416]
### Is your proposal related to a problem?

Dictionary terms can be added to a dataset in two different ways - one at the dataset level (on the overview tab) and secondly at a column level (on the structure tab)

When looking at the linked terms in the dictionary it only shows datasets where the term was added on the overview tab and not at a column level.

### Describe the solution you'd like

It would be fantastic to have all datasets listed within the linked terms regardless of if it was linked at an overview or column level

### Additional context
<img width="960" alt="linked items" src="https://github.com/opendatadiscovery/odd-platform/assets/4620433/dca09175-23fe-4731-8391-197567f72db8">

Above is an example of the issue / limitation - I'm assuming this may be due to the fact of column level labelling only coming in later releases

ODD-Platform v0.15.0

**Comment by damirabdul** [comment]
Hey, @clintjb . You are correct, we have added terms to columns later, that's why they are not shown in linked items tab. This is good proposal, we will schedule this feature to one of our next releases, thanks!

**Comment by RamanDamayeu** [comment]
Proposal:
1. New tab "Linked columns"
 1.1 (TBD) properties: entity, business name, data type  
2. Rename tab "Linked items" --> "Linked entities"
3. Calculate total as "Linked items" + "Linked columns"

**Comment by clintjb** [comment]
Proposal sounds really good - this should give a solid overview while still allowing a clean segregation between the types of links...
Perfect!
