### ISSUE TITLE
Labels Within Dictionary Terms

### ISSUE THREAD

**Issue by clintjb** [opendatadiscovery/odd-platform#1417]
### Is your proposal related to a problem?

With dictionary terms we can allocate tags but not labels - as terms can / are linked to a column and columns have tags this "consistency" is extremely useful for the business.

### Describe the solution you'd like

We would like to see a label area within the dictionary term (identical to that of the tag area)

### Additional context

<img width="960" alt="labels" src="https://github.com/opendatadiscovery/odd-platform/assets/4620433/dea26732-5c52-4e97-885f-19f175ec912b">

Sample mock-up can be seen above

**Comment by damirabdul** [comment]
Hi, @clintjb,

Thank you for your proposal.

Initially, we assumed that terms could only be described with tags that are specifically related to that particular term. Column labels are distinct and should not be duplicated within the term.

Could you please elaborate on your use case? We'd like to understand why having labels for terms is beneficial for you.

**Comment by damirabdul** [comment]
Will be resolved via #1425

**Comment by clintjb** [comment]
@damirabdul - all clear after the discussion the other day and makes perfect sense....
Thanks very much and will keep an eye out for removal of the labels / integration of tags at the column / structure level...
Cheers
