### ISSUE TITLE
Get rid of labels

### ISSUE THREAD

**Issue by damirabdul** [opendatadiscovery/odd-platform#1425]
Initially, we implemented two methods for tagging:

1. Tags specific to data entities.
2. Labels specific to dataset fields.

This distinction was made to avoid mistakenly assigning dataset field tags to data entities. However, we've observed that this separation has caused confusion among users. As a result, we've decided to streamline the system by eliminating labels and universally applying tags.

During this transitional phase, it's crucial that no information is lost. All existing labels should be converted and retained as tags. Furthermore, we must also consider aspects like activity logging and security permissions.

**Comment by RamanDamayeu** [comment]
Possible impact on the odd-collector-profiler as it updates labels of columns: https://github.com/opendatadiscovery/odd-collector-profiler/issues/22

**Comment by indiealexh** [comment]
> Initially, we implemented two methods for tagging:
> 
> 1. Tags specific to data entities.
> 2. Labels specific to dataset fields.
> 
> This distinction was made to avoid mistakenly assigning dataset field tags to data entities. However, we've observed that this separation has caused confusion among users. As a result, we've decided to streamline the system by eliminating labels and universally applying tags.
> 
> During this transitional phase, it's crucial that no information is lost. All existing labels should be converted and retained as tags. Furthermore, we must also consider aspects like activity logging and security permissions.

Appreciate the clarification, I was unsure what the difference was other than the priority value.

**Comment by RamanDamayeu** [comment]
Issue to replace labels with tags in data profiler: https://github.com/opendatadiscovery/odd-collector-profiler/issues/27
