### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by SamuelAdamsMcGuire** [opendatadiscovery/odd-platform#1442]
### Is your proposal related to a problem?

We have non-slack users that are also interested in getting alerts via email

### Describe the solution you'd like

Add a simple field to specific alerts that a user can enter an email to receive updates

### Describe alternatives you've considered

Using something like python logging handlers or whatever is available in the respective data entity

### Additional context

NA

**Comment by AndreyNenashev** [comment]
Hey, @SamuelAdamsMcGuire! Right now we don't support directive notifications on specific alerts - it requires to enhance current notifications system on levels and it's on roadmap.
**Proposal solution:** 

- We will add possiblity to add list of emails on data entity alerts notification settings. This email list will apply the same rules as other notifications.

**Comment by SamuelAdamsMcGuire** [comment]
@AndreyNenashev  Thanks for the feedback. Keep me posted. I currently have a simple work around and use the email alerts from Great Expectations. However a general alert from the platform would be great.

**Comment by Vladysl** [comment]
Implemented in https://github.com/opendatadiscovery/odd-platform/pull/1489

**Comment by Vladysl** [comment]
Implemented email smpt notifications
to use it you should fill this properties 
notifications:
  enabled: true
   email:
      sender: your_sender_email
      password: password
      smpt: smpt_host
      port: smpt_port
      notification:
        emails: "yourFirst@gmail.com,yourSecond@gmail.com"
Docs:        
google smpt - https://support.google.com/a/answer/176600?hl=en
(in case you have google 2factor auth - https://support.google.com/accounts/answer/185833?visit_id=638338654265262930-3223924282&p=InvalidSecondFactor&rd=1)
aws smpt - https://repost.aws/knowledge-center/ses-set-up-connect-smtp

sender, password, smpt and notification.emails is mandatory in case you want to enable email notifications
