### ISSUE TITLE
Dictionary Terms are Not rendering properly when we add it the columns 

### ISSUE THREAD

**Issue by mavenzer** [opendatadiscovery/odd-platform#1464]
**Dictionary Terms Are Not Rendering as Intended**

In the most recent version of ODD-Platform: 0.16, markdown is supported in it. But whenever  we are linking those terms at a column level the  Dictionary terms are not rendering properly.

<img width="952" alt="datamesh" src="https://github.com/opendatadiscovery/odd-platform/assets/24300927/faab3351-d864-4a1d-9ba6-2cbc3e23c56e">

**Comment by AndreyNenashev** [comment]
Hey @mavenzer ! nice catch! Thanks for pointing out! It will be resolved in [0.17](https://github.com/opendatadiscovery/odd-platform/milestone/17)
