### ISSUE TITLE
Add description and correct examples for the set of "ingestion" endpoints for Swagger

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-platform#1518]
At the moment there are not correct descriptions and examples for this set of endpoints:
```
/ingestion/metrics
/ingestion/entities/datasets/stats
/ingestion/entities
/ingestion/datasources
/ingestion/alerts
/ingestion/entities/degs/children
/ingestion/alert/alertmanager
```

We need to sync descriptions with https://github.com/opendatadiscovery/opendatadiscovery-specification/blob/main/specification/entities.yaml and  https://github.com/opendatadiscovery/opendatadiscovery-specification/blob/main/specification/metrics.yaml

**Comment by Vladysl** [comment]
implemented in https://github.com/opendatadiscovery/odd-platform/pull/1537
