### ISSUE TITLE
[QUERY EXAMPLES] Not listed all Linked entities on Dataset page

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-platform#1530]
When we look for Linked entities on a main page for Query Example we correctly see all the linked to that query datasets. 
When we look for Linked entities on "Query Example" tab on a Dataset page we see only one linked entity - the same from what page we are at the moment.

Example of correct list on the main Query Examples page:
![correct_list_of_limked_entities](https://github.com/opendatadiscovery/odd-platform/assets/28390761/ab44e0a7-7450-4e73-bba9-e34f526675de)

Example for the same case but from "users" table page with limited to only one linked entity:
![limited_list_of_limked_entities](https://github.com/opendatadiscovery/odd-platform/assets/28390761/6ef04909-ad48-4be8-b576-b61cea0026be)

**Comment by Vladysl** [comment]
implemented in https://github.com/opendatadiscovery/odd-platform/pull/1533
