### ISSUE TITLE
Create new Query Example permission policy 

### ISSUE THREAD

**Issue by Vladysl** [opendatadiscovery/odd-platform#1568]
Create new Policy QUERY_EXAMPLE
Create new Policy Permissions:
QUERY_EXAMPLE_UPDATE(belongs to QUERY_EXAMPLE),
QUERY_EXAMPLE_DELETE(belongs to QUERY_EXAMPLE),
QUERY_EXAMPLE_DATASET_CREATE(belongs to DATA_ENTITY),
QUERY_EXAMPLE_DATASET_DELETE(belongs to DATA_ENTITY).

Condition field - "queryexample:name"

FE part:
- host/management/policies - should accept new policy type  QUERY_EXAMPLE
- host/data-modelling/query-examples/{query_example_id}- should perform /api/resource/QUERY_EXAMPLE/{query_example_id}/permissions request to retrieve allowed policies for current user
- host/dataentities/{data_entity_id}/query-examples - should take allowed policies from /api/resource/DATA_ENTITY/{data_entity_id}/permissions request
- changed API for create/delete queryExample To Data Entity relations

**Comment by RamanDamayeu** [comment]
Please, also consider updating documents https://docs.opendatadiscovery.org/configuration-and-deployment/enable-security/authorization

**Comment by anatolii-yemets** [comment]
Working branch is [https://github.com/opendatadiscovery/odd-platform/tree/1568](https://github.com/opendatadiscovery/odd-platform/tree/1568)
