### ISSUE TITLE
unable to run locally

### ISSUE THREAD

**Issue by bharath4kumar** [opendatadiscovery/odd-platform#1569]
**Describe the bug**
Receive this error when building the platform:

> odd-platform-ui@0.1.0 prepare C:\odd-platform\odd-platform-ui
> chmod u+x .husky/prepare.sh && .husky/prepare.sh

'.husky' is not recognized as an internal or external command,
operable program or batch file.
 ELIFECYCLE  Command failed with exit code 1.

> Task :odd-platform-ui:pnpmInstall FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':odd-platform-ui:pnpmInstall'.

**Set up**

4572bba

**Comment by Vladysl** [comment]
Hello
In case you want to run it locally, I suggest you to try run it using docker compose. 
Otherwise, if you want to deep dive into the code base, we need to take a look on this.

**Comment by AndreyNenashev** [comment]
In your case it seems you don't have all prerequisites installed locally. If you want to build and run platform locally you need to follow this instruction. 
https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform
Prerequisites https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform#prerequisites

**Comment by anatolii-yemets** [comment]
@bharath4kumar We'd like to let you know that we've tweaked the ui build to better support Windows OS, but you need to use a Bash compatible shell https://github.com/opendatadiscovery/odd-platform/blob/main/odd-platform-ui/README.md

Here's an example of how to set this up
`npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`

This will allow you to build the ui (and by extension the platform itself) on Windows.
