### ISSUE TITLE
Add default behabior for lookup tables schema configuration

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-platform#1584]
If we do not have a configuration set for look up tables storage (postgres schema where real tables should be stored) let's have a default behavior to use new "lookup_tables_schema" within the same database where the system tables are stored

Here is the list of configs to set up lookup tables schema:
      - SPRING_CUSTOM-DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DATABASE}?schema=lookup_tables_schema
      - SPRING_CUSTOM-DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_CUSTOM-DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

**Comment by Vladysl** [comment]
Implemented in https://github.com/opendatadiscovery/odd-platform/pull/1600
