### ISSUE TITLE
[DATA QUALITY DASHBOARD]. Add filters

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-platform#1590]
The idea is to add some interactivity to the Data Quality Dashboard so that users could filter out results to be shown on the dashboard by

- Namespace
- Datasource
- Ownership Owner
- Ownership Title
- Tag

of the Data Quality Tests and of Data Entity (Tables).

Additional considerations:

- We should consider the a user would filter out information for Data Quality Tests and/or Data Entity (Tables);
- We should consider possibility to add more than 1 filter at a time (so we could choose Namespace and Tag together, for instance);
- Each filter should let choose multiple values (for instance, if we choose to filter by Namespace we could choose NamespaceA and NamespaceB simultaneously);
- For simplicity let's assume that only AND logical operator should be implemented at the moment, so all conditions should be joined by logical conjunction;

**Comment by anatolii-yemets** [comment]
During internal discussion we identified that there should be 10 fields visible (5 filters for tables and 5 for tests).

The overall view should look something like this:
![image](https://github.com/opendatadiscovery/odd-platform/assets/106543964/bc90afe3-ecc0-4f37-8b6c-4c282722b758)
