### ISSUE TITLE
Owner / Username Association Issues

### ISSUE THREAD

**Issue by clintjb** [opendatadiscovery/odd-platform#1622]
**Describe the bug**
There are two topics linked to owners roles and the usernames being associated. Firstly after logging in and associating the username with an owner its impossible to remove that username after its been accepted by an admin.
Secondly if a user is configured as an admin within the deployment configuration its still possible to remove the admin rights (it seems to ignore the deployment configuration)

**Set up**
ODD Platform on K8s (23.1) utilizing HELM deployment

**Steps to Reproduce**
- Here you will see the logged in user (which is configured as an admin in the deployment config) associates themselves an owner (John Doe in this case) 
- The owner you see has three roles (one of which is administrator)
- The user can than remove the admin role from that owner (you will see its successfully updated)
- After logging back in you will see there's no further access to create owners / edit etc which seems to imply the username configured within the deployment config is now being ignored.
- Please see images below for more details

**Expected behavior**
- Admins shouldn't be able to remove their own access / deployment config should remain
- On the edit owner tab a list of associated usernames should be shown and accordingly removable

**Screenshots**
![1 - Owner Allocation](https://github.com/opendatadiscovery/odd-platform/assets/4620433/22efbde1-af12-479b-aaaf-c224a93a39d3)
![2 - Owner Roles](https://github.com/opendatadiscovery/odd-platform/assets/4620433/bed3a077-d0de-47a3-9f7f-fb6ca3c9a909)
![3 - Removal Of Role](https://github.com/opendatadiscovery/odd-platform/assets/4620433/6358c855-2e29-4d78-a37c-45bfe3583b76)
![4 - Loss Of Access](https://github.com/opendatadiscovery/odd-platform/assets/4620433/decbe4b8-4180-48cf-930c-5fd710900120)

![Proposed Solution](https://github.com/opendatadiscovery/odd-platform/assets/4620433/432ecece-fade-4d73-bb78-75503127efb8)

**Comment by RamanDamayeu** [comment]
**Proposed functionality:**

Three tabs on "Associations"
1. New Requests
  1.1 User - Owner - Role - Provider
  1.2 Functionality to Accepted/Declined requests
  1.3 Create Association
2. Active Associations
  2.1 User - Owner - Role - Provider - Resolved by - Resolved At
  2.2 Functionality to unlink existing associations
3. History (note, Read only)
  3.1 User - Owner - Role - Provider - Resolved by - Resolved At
  
  
**User Flows:**  
1. User wants to create an association to be linked to a specified Owner:
  1.1 If Admin Accepts the request --> the record is added to "Active Associations" --> the record is added to "History" with status Accepted 
  1.2 If Admin Rejects the request --> the record is added to "History" tab only with status Declined
2. Admin wants to unlink the existing Association
  2.1 On the "Active Associations" calls unlink functionality for a record --> Record disappears from "Active Associations" --> record is added to "History" with status Declined
3. Admin wants to create a new Association
  3.1  On the "New Requests" tab Admin call the functionality to create an association --> the record is added to Active Associations --> the record is added to History with status Accepted
4. Admin wants to change Association for a given user
  4.1 On the "New Requests" tab Admin call the functionality to create an association for the same user with a different Owner --> The system automatically unlinks existing Association --> record is added to History with the information that the Association has been Declined --> the record is added to Active Associations with the new owner assigned --> the record is added to History with the new association and status Accepted
  
@clintjb are you ok with this suggested implementation to create/update/delete associations between Users and Owners?

**Comment by Vladysl** [comment]
implemented in https://github.com/opendatadiscovery/odd-platform/pull/1638
