### ISSUE TITLE
Redshift: Failed to load metadata for tables: 1 validation error for DataEntity owner

### ISSUE THREAD

**Issue by snexuz** [opendatadiscovery/odd-platform#1676]
**Describe the bug**
 odd_collector.adapters.redshift.adapter:get_data_entity_list:74 - Failed to load metadata for tables: 1 validation error for DataEntity  owner

**Set up**
From this repo, and ran by docker-compose on AWS EC2.

**Steps to Reproduce**
1. Everything looks fine, until I try to collect metadata from our own Redshift data warehouse.
2. collector_config.yaml is fine, and we can see odd platform extract metadata out of Redshift.
3. I'd try to add try, except to get_data_entity_list(), and notice most errors were on view tables.

**Expected behavior**
Extract metadata from Redshift

**Screenshots**
(If applicable, add screenshots to help explain your problem)
![image](https://github.com/opendatadiscovery/odd-platform/assets/5488329/cd43e8cf-27a6-4cfd-ab6e-106fa79dd7f7)

**Comment by snexuz** [comment]
Thanks for your beautiful works, it works fine now.

**Comment by ValeriyWorld** [comment]
closed and merged in main with PR: https://github.com/opendatadiscovery/odd-collectors/pull/75
