### ISSUE TITLE
Spellcheck Integration

### ISSUE THREAD

**Issue by clintjb** [opendatadiscovery/odd-platform#1678]
### Is your proposal related to a problem?

When multiple users are updating descriptions or enriching dictionary terms we see a reasonable frequency of spelling mistakes (we maybe also need to find team members who can spell 🤦)

### Describe the solution you'd like

Ideally an integrated spell check solution (be it browser whatever) where within description fields there would be an underlining of mistakes for the user to fix.

**Comment by AndreyNenashev** [comment]
Hey @clintjb ! Thanks for noticing. We will enable default native browser spellcheck for the textarea fields. Like this
<img width="962" alt="Screenshot 2024-05-30 at 11 35 18" src="https://github.com/opendatadiscovery/odd-platform/assets/2155083/6a3ea325-9815-4f07-a3a3-5aeceead551d">

**Comment by clintjb** [comment]
Perfect, yes think native browser is more than adequate 👍
