### ISSUE TITLE
Tags are not being cascaded  for the terms which are linked to the Data-entity Structure. 

### ISSUE THREAD

**Issue by mavenzer** [opendatadiscovery/odd-platform#1688]
With the recent release of ODD-Platform (0.27.0), we have observed an unusual behavior when linking terms to the data-entity structure. Specifically, the tags associated with the terms are not being carried over, despite the terms themselves having tags.

For additional context, please refer to the attached screenshots. Notably, the tags are not visible at the term level.

![tag](https://github.com/opendatadiscovery/odd-platform/assets/24300927/404a9d18-b8b9-4126-86c2-1e005ec201de)

For the data-Entity where we have linked the terms with the tags.  We cannot see the tags being cascaded down to the terms. 

![date-e](https://github.com/opendatadiscovery/odd-platform/assets/24300927/886104b8-77db-49f1-a053-7164677ba941)

![terms](https://github.com/opendatadiscovery/odd-platform/assets/24300927/9667070d-b17f-456e-bd42-6b7c8bbf644b)

**Comment by RamanDamayeu** [comment]
Hi @mavenzer! I just wanted to clarify whether the functionality expectations match.

In the release 0.26.0, we added the ability to assign a term to another term directly or through definition. So now we can essentially build a “knowledge graph” by referencing from one term to another (and with some additional context if we use reach text in definitions). And we can still specify terms at the date entity level. 
But no tags were added to the terms. This functionality to indicate a tag on a term is not yet available at all...

**Comment by clintjb** [comment]
Hi @RamanDamayeu
Maybe just to jump in - totally understand the term to term linking... Issue is it seems the tag area has now been removed (see screenshot and highlighted area) previously it was able to see which tags were associated with that term as well as edit / add / remove etc - this area now no longer exists - hope this is a little clearer
 
![image](https://github.com/opendatadiscovery/odd-platform/assets/4620433/d7ff36be-c235-42c4-9a30-ff1bda5bde24)

**Comment by Vladysl** [comment]
PR - https://github.com/opendatadiscovery/odd-platform/pull/1689

**Comment by mavenzer** [comment]
Thanks a lot
