### ISSUE TITLE
Bug: Entities doubling in search suggestion

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#237]
When you enter a search query, two identical entities with different IDs come in the response.
<img width="1186" alt="Screenshot 2021-11-10 at 16 42 09" src="https://user-images.githubusercontent.com/59020701/141124338-5d95ed11-6ec6-4d0a-b999-139db8c868bc.png">
<img width="1003" alt="Screenshot 2021-11-10 at 16 42 57" src="https://user-images.githubusercontent.com/59020701/141124348-d72e8c58-67ef-4b74-b6f2-3ed4b597c7ec.png">

**Comment by DementevNikita** [comment]
demo stand contains several duplicating data sources. Not a bug
