### ISSUE TITLE
New Feature: Big Query integration

### ISSUE THREAD

**Issue by Jujubalandia** [opendatadiscovery/odd-platform#353]
Will be nice to have this product integrated with Bigquery, one of the most widely common data warehouse

**Comment by DementevNikita** [comment]
Hey @Jujubalandia!
Thank you for the feature request! We will to add this into our roadmap and keep you updated here

**Comment by alexeyzavyalov** [comment]
Duplicate of #61

**Comment by DementevNikita** [comment]
hey @Jujubalandia, sorry it took so long.
https://github.com/opendatadiscovery/odd-collector-gcp

now we have an integration of BigQuery, please take a look. If you have more questions and bug reports, please feel free to create issues in odd-collector-gcp repository
