### ISSUE TITLE
Console warning: Encountered two children with the same key

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#363]
**Describe the bug**
Console warning `Encountered two children with the same key`

**Steps to Reproduce**

1. Go to Alerts page -> scroll alerts - check console.
2. Go to search page -> switch between entity type tabs -> check console.

**Expected behavior**
No warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/59020701/149765893-ccd90817-4885-4a27-96fc-c252e64cf68e.png)

**Additional context**
Check another project pages and functionality.

**Comment by Denisalik** [comment]
Closed, because it is a backend issue. Created a new issue for it, with a backend label. [It can be found here](https://github.com/opendatadiscovery/odd-platform/issues/400)
