### ISSUE TITLE
Display Platform version.

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#388]
### Describe the solution you'd like

Needs to see Platform version in the UI.

### Additional context

[Figma styles](https://www.figma.com/file/yiL1CRyHsOEeY45NesWdiC/ODD?node-id=955%3A25721)

**Comment by DementevNikita** [comment]
seems like a duplicate for https://github.com/opendatadiscovery/odd-platform/issues/308
