### ISSUE TITLE
Status of puller condition.

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#389]
### Is your proposal related to a problem?

Sometimes i don't understand whether the puller works or not?

### Describe the solution you'd like

Add puller work status and time of the latest pull.

### Additional context

[Figma styles](https://www.figma.com/file/yiL1CRyHsOEeY45NesWdiC/ODD?node-id=955%3A27146)

**Comment by DementevNikita** [comment]
duplicate of https://github.com/opendatadiscovery/odd-platform/issues/355
