### ISSUE TITLE
Migration from redux to redux-toolkit

### ISSUE THREAD

**Issue by alinamiryuk** [opendatadiscovery/odd-platform#527]
To improve performance and reduce the boilerplate, need to migrate to the redux toolkit.
Need to refactor actions, thunks, reducers and related components.

- [x] #757
- [x] #787
- [x] #750
- [x] #894
- [x] #790
- [x] #847
- [x] #749
- [x] #748
- [x] #846
- [x] #745
- [x] #895
- [x] Migrate Namespace section to Redux toolkit
- [x] Migrate Lineage section to Redux toolkit

**Comment by Leshe4ka** [comment]
All tasks completed
