### ISSUE TITLE
Add content placeholders for loading page content.

### ISSUE THREAD

**Issue by soffest** [opendatadiscovery/odd-platform#55]
- [ ] Data Entity Details: Overview
- [ ] Data Entity Details: Structure
- [ ] Data Entity Details: Lineage
- [ ] Data Entity Details: Test Reports
- [ ] Search Results
- [ ] Search Filters
- [ ] Home Page

**Comment by DementevNikita** [comment]
Duplicate of https://github.com/opendatadiscovery/odd-platform/issues/32
