### ISSUE TITLE
Truncate big numbers in the `rows` column of datasets

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-platform#606]
**Describe the bug**
Big numbers must be truncated on the search page. Let's start from the 10K so that every number more than 10_000 became 10K 
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/53081563/166706138-75399e51-b4ce-4dee-b55a-11fabaaf9391.png">

**Comment by Leshe4ka** [comment]
Resolved in #676
