### ISSUE TITLE
Fix search vectors for data entity

### ISSUE THREAD

**Issue by damirabdul** [opendatadiscovery/odd-platform#607]
Nowadays we don't handle situations when tag or owner was removed, e.g. we don't update search vectors for affected data entities.
1. Use soft delete for all relation tables (e.g. tag_to_data_entity, ownership)
2. Update search vectors in all cases:
    a. Relation was added/removed
    b. Related entity was updated (tag renamed, role renamed etc.)
    c. Related entity was deleted

**Comment by DementevNikita** [comment]
Tied with reactive refactoring:
https://github.com/opendatadiscovery/odd-platform/projects/5
