### ISSUE TITLE
Support BigQuery integration

### ISSUE THREAD

**Issue by yu-iskw** [opendatadiscovery/odd-platform#61]
## Motivation
As `odd-platform` supports redshift and so on, it would be awesome to support BigQuery integration.

**Comment by germanosin** [comment]
Hi, @yu-iskw. Thanks for creating feature request. This one is looks really interesting. We'll take it in our plan.

**Comment by DementevNikita** [comment]
hey @yu-iskw, sorry it took so long.
https://github.com/opendatadiscovery/odd-collector-gcp

now we have an integration of BigQuery, please take a look. If you have more questions and bug reports, please feel free to create issues in odd-collector-gcp repository
