### ISSUE TITLE
Add system fields to data_entity table

### ISSUE THREAD

**Issue by damirabdul** [opendatadiscovery/odd-platform#628]
We have `created_at` and `updated_at` fields in data_entity table, which are holding values, which came from collectors. However, in all other tables these fields are system fields and holding info about when row appears in our database.

Need to add additional fields, e.g. `external_created_at` and `external_updated_at` at fill them with external values and use `created_at` and `updated_at` fields for internal updates

**Comment by adyachenkoprov** [comment]
@DementevNikita let me take it
