### ISSUE TITLE
Display datasource name in search suggestion

### ISSUE THREAD

**Issue by Leshe4ka** [opendatadiscovery/odd-platform#631]
Needs to implement ability to display datasource name in search suggestion.
[Design](https://www.figma.com/file/yiL1CRyHsOEeY45NesWdiC/ODD?node-id=955%3A25730)

**Comment by DementevNikita** [comment]
closing this in order to encapsulate all search explanations feature requests in https://github.com/opendatadiscovery/odd-platform/issues/336
