### ISSUE TITLE
Beautify ENUM names for data entity class filter

### ISSUE THREAD

**Issue by damirabdul** [opendatadiscovery/odd-platform#632]
Currently in dictionary in linked items we have entities class filter, which looks this way
![image](https://user-images.githubusercontent.com/5929071/167895520-62895416-ceef-4e5c-8b31-625120d9b324.png)

Need to replace these values with more readable ones, like on tabs at main page

**Comment by DementevNikita** [comment]
It doesn't seem to me as the frontend-scoped task, since we are sending those values from backend.
Am I right to assume that @damirabdul?

**Comment by damirabdul** [comment]
> It doesn't seem to me as the frontend-scoped task, since we are sending those values from backend. Am I right to assume that @damirabdul?

It's not so simple. We have enums specified in our openapi contract and now we are sending these enums to frontend, not just strings. Therefore, changes will affect FE side as well
