### ISSUE TITLE
Replace `is_deleted` with `deleted_at` field in ODD Platform models

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-platform#639]
### Summary:

In ODD Platform we don't physically delete entities. Instead we are using logical deletion, which means we just set deletion flag for the database row.
Previously we used just boolean flag for these purposes, but then we decided, that we want to know when row was deleted. Therefore instead of boolean flag we added additional field **deleted_at**.

There are some tables in platform, which still doesn't have such fields:

- metadata_field
- owner
- tag
- role

We already have logic which set a value in this field, it's just needed to add such column to above tables and pass it in repository constructors.

### Acceptance criteria:

When any of above entities is deleted, delete time should be saved in database.

**Comment by theorangeclockwork** [comment]
@damirabdul can you assign me to this issue?

**Comment by DementevNikita** [comment]
@theorangeclockwork done.

please let us know if you have any questions whatsoever. You can PM us directly via our [Slack community](https://go.opendatadiscovery.org/slack)

**Comment by DementevNikita** [comment]
@theorangeclockwork any luck with this issue?

**Comment by theorangeclockwork** [comment]
@DementevNikita started yesterday, was quite busy last weeks
doing well so far

**Comment by DementevNikita** [comment]
awesome!
let us know if you need anything
