### ISSUE TITLE
The search field on Catalog page doesn't work in a proper way 

### ISSUE THREAD

**Issue by nstkvl** [opendatadiscovery/odd-platform#824]
**Set up**
https://platform.dev.odd.provectus.io/search/4171e6c9-11b0-43b2-8625-a5528adb2c8f

**Steps to Reproduce**
1. Login
2. Go to Catalog page 
3. Try to type "123" in the Search field
4. Tap Enter
5. Delete "123" from the Search field
6. Reload the page

**Expected result**
The search result is updated. The user can see all data without filtering by the search request. The search field is empty.

**Actual result**
The search field is not empty it is pre-filled with the last search request. Data is filtered by the last search request. The user can reload the data view only by switching to Management page and back. 

**Screenrecord**
https://recordit.co/KbIoVkS4yu

**Comment by DementevNikita** [comment]
Thank you @nstkvl!

This is a part of preserving search attributes feature. This way users can share search attributes by copying the URL.

**Comment by nstkvl** [comment]
Got you @DementevNikita  Thank you for clarifying.
