### ISSUE TITLE
Name of the the button "Add custom name" and label in modal window are not the same on Dataset page

### ISSUE THREAD

**Issue by nstkvl** [opendatadiscovery/odd-platform#831]
**Set up**
https://platform.dev.odd.provectus.io/dataentities/24027406/overview

**Steps to Reproduce**

1. Login with valid data
2. Go to the Catalog page
3. Open Datasets
4. Open some dataset from the list
5. Tap on "Add custom name" button 
6. Pay attention to the name of the label on the modal window that appears  

**Expected result**
The name of the button and label should be the same. Need some discussion about which exact name should be 

**Actual result**
The name of the button and label are different. 

**Attachment** 
https://recordit.co/yuwg1biVFQ

**Comment by nstkvl** [comment]
@Anna-EG

**Comment by Anna-EG** [comment]
@DementevNikita @nstkvl 
When we enter a new name, it replaces the original one. So "add" the name is not exactly what we do here. I would like to suggest "Edit name" for the button instead of "Add custom name" and "Edit datasource name" as a title for the modal window.

**Comment by Leshe4ka** [comment]
> 

For button will be "Edit name"
For title of the modal will be the same, because user can edit not only datasource names, but also the names of entities of all types.
