### ISSUE TITLE
TestPage: Severity is null

### ISSUE THREAD

**Issue by a-chumagin** [opendatadiscovery/odd-platform#868]
**Describe the bug**
(A clear and concise description of what the bug is.)

**Set up**
version: ODD Platform v.v0.6.0-beta-2
add tests to ODD and setup severity , for instance "Critical"

**Steps to Reproduce**

1. Open the test page  (for instance , {odd_host}/dataentities/{test_id}/overview
2. Check Severity
3. Severity is null 
![image](https://user-images.githubusercontent.com/3287939/181211084-5e5b354c-41d0-4447-b71f-52af4c6e42d9.png)

**Expected behavior**
Severity is "Critical"

**Comment by Leshe4ka** [comment]
According to @DementevNikita we shouldn't display severity at this page.
