### ISSUE TITLE
User receives 500 error code while trying to open any activity

### ISSUE THREAD

**Issue by nstkvl** [opendatadiscovery/odd-platform#878]
**Set up**
https://platform.dev.odd.provectus.io/activity?beginDate=1658696399999&endDate=1659214799999&size=20&type=ALL

**Steps to Reproduce**

1. Login with valid data
2. Go to Activity page
3. Pay attention to the counter on All tab
4. Tap on some activity

**Expected result**
User can open details

**Actual result**
User receives 500 error code

**Attachment**
https://recordit.co/Ap4DGIpYT6

**Comment by DementevNikita** [comment]
Cannot reproduce at the moment

**Comment by damirabdul** [comment]
closed by #235
