### ISSUE TITLE
Remove metadata blocks from search if they are empty

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-platform#918]
<img width="520" alt="Screenshot 2022-08-15 at 12 17 09" src="https://user-images.githubusercontent.com/53081563/184609599-f6507812-189d-42c6-8260-4a0ed38ada68.png">

**Comment by Leshe4ka** [comment]
On the last ODD design sync was decided to show to the user empty metadata block (and description) in the preview. For better understanding that the entity is not filled.
