### ISSUE TITLE
Dataset structure is not available when first first upload fails

### ISSUE THREAD

**Issue by VRabinin** [opendatadiscovery/odd-platform#933]
**Describe the bug**
When ingestion fails (partially) with HTTP500, for some tables field structure is not registered. Records exist for fields in the table dataset_field, but tables dataset_structure and dataset_version are not populated. Upon the next ingestion cycle, even if it goes well, the structure is not registered which created a permanent issue.
For the objects with this issue also (upstream) lineage is not displayed in the graph, but the objects are present in the Transformer list

**Set up**
ghcr.io/opendatadiscovery/odd-platform:0.6.1-arm

**Steps to Reproduce**

1. Load DataEntity with Data Transformer with inputs oddrn's which are missing in the platform

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by DementevNikita** [comment]
Thank you for letting us know!

This is a known issue, will be fixed in the 0.7 release
