### ISSUE TITLE
Sort entities inside of a DEG alphabetically by their names

### ISSUE THREAD

**Issue by DementevNikita** [opendatadiscovery/odd-platform#940]
## Useful information
Here are some useful links and information if you are new to this repository and OpenDataDiscovery system

### Documentation
We keep all documentation in our [GitBook](https://docs.opendatadiscovery.org/). It contains all kind of information such as
system overview and use cases (why are we doing this), architecture (how are we doing this), etc.
Please take a look at the `Developer Guides` section where we explain [how to contribute](https://docs.opendatadiscovery.org/developer-guides/how-to-contribute) and
[how to setup local environment](https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform)

### Contact us
If you're struggling with something, please feel free to ask us anything here in the GitHub issue ticket or via our [Slack community](https://go.opendatadiscovery.org/slack).

**Comment by Nyadzayo** [comment]
@DementevNikita can you assign to me this issue

**Comment by DementevNikita** [comment]
@Nyadzayo sure thing!

@Leshe4ka, could you please provide a context for this task and support if needed?

**Comment by Leshe4ka** [comment]
@Nyadzayo nice to meet you! 
In the Data Entity Details -> Lineage, we have got a few types of cards (f.e. DS, TS, DEG). And lineage card of DEG (data entity group) type have got the ability to show which entities there are inside of this DEG. List of the internal entities we displaying inside a modal window (GroupedEntitiesListModal view). So in this task it's necessary to sort list of entities inside of DEG alphabetically by their names.

If you will need a support with running project locally or with data for testing - contact me, ow we will make a call.

**Comment by Nyadzayo** [comment]
@Leshe4ka can we get in touch on setting up the project to run locally then i implement the feature

**Comment by DementevNikita** [comment]
@Nyadzayo the best way to do so is to join our Slack community.
https://go.opendatadiscovery.org/slack

please don't hesitate to contact @Leshe4ka or me directly.

**Comment by DementevNikita** [comment]
@Nyadzayo any luck with this issue?
