### ISSUE TITLE
`getDataEntityGroupLineage` throws NPE if DEG lineage has nodes

### ISSUE THREAD

**Issue by esmeneev** [opendatadiscovery/odd-platform#958]
**Describe the bug**
(A clear and concise description of what the bug is.)

Endpoint for DEG lineage returns 500 error if the lineage is not empty. This happens for following reasons:

https://github.com/opendatadiscovery/odd-platform/blob/8367f0a8ed01be88ad8bbf4ffbfec7f357de635c/odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/service/LineageServiceImpl.java#L78 - `groupsRelations` property of `DataEntityLineageStreamDto` is set as null here

https://github.com/opendatadiscovery/odd-platform/blob/8367f0a8ed01be88ad8bbf4ffbfec7f357de635c/odd-platform-api/src/main/java/org/opendatadiscovery/oddplatform/mapper/LineageMapperImpl.java#L58 - this variable is set to null, so when we do `groupsRelations.get()` in a loop iterating over lineage nodes few lines down, we get NPE. 

**Set up**
(How do you run the app?
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)

Running locally, reproducible on 0.6.3

**Steps to Reproduce**

1. `curl http://localhost:8080/api/dataentitygroups/{deg_id}/lineage`

**Expected behavior**
(A clear and concise description of what you expected to happen)

DEG lineage is returned

## Useful information
Here are some useful links and information if you are new to this repository and OpenDataDiscovery system

### Documentation
We keep all documentation in our [GitBook](https://docs.opendatadiscovery.org/). It contains all kind of information such as
system overview and use cases (why are we doing this), architecture (how are we doing this), etc.
Please take a look at the `Developer Guides` section where we explain [how to contribute](https://docs.opendatadiscovery.org/developer-guides/how-to-contribute) and
[how to setup local environment](https://docs.opendatadiscovery.org/developer-guides/build-and-run/build-and-run-odd-platform)

### Contact us
If you're struggling with something, please feel free to ask us anything here in the GitHub issue ticket or via our [Slack community](https://go.opendatadiscovery.org/slack).

**Comment by DementevNikita** [comment]
Probably is tied with #656
