### ISSUE TITLE
MG STUDIO

### ISSUE THREAD

**Issue by Blaze09107** [opendatadiscovery/odd-platform#963]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(Describe your proposed solution here.)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by DementevNikita** [comment]
Closing due to a lack of information. Please feel free to recreate a ticket with additional information about feature request.
