### ISSUE TITLE
Issue with connecting to MySQL server

### ISSUE THREAD

**Issue by colebagozzi** [opendatadiscovery/odd-platform#979]
**Describe the bug**
(A clear and concise description of what the bug is.)
When trying to run the demo, I tried t configure a local mysql database, and could not get it to configure. I have tried removing the postgresql dataset and inserting the mysql call "mysql.yaml" as well as tried configuring the ODDRN to where the database was stored. An guidance would be appreciated. 

**Set up**
(How do you run the app?
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)
I am running v. 6.3 in a docker image (v20.10.17)

**Steps to Reproduce**

1.

**Expected behavior**
(A clear and concise description of what you expected to happen)

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by Vixtir** [comment]
Hello, @colebagozzi 
Did you rename `demo.yaml` or `collector-config.yaml` .Do not rename `collector-config.yaml`, collector uses that file for creating connection.

Steps
1. Run `demo.yaml`, create token for collector how it was written in [readme](https://github.com/opendatadiscovery/odd-platform/tree/main/docker#step-2-configuring-and-running-collector-to-gather-metadata-from-the-sample-data-source)
2. Configure `collector-config.yaml` for using mysql adapter [readme](https://github.com/opendatadiscovery/odd-platform/tree/main/docker#configure-and-run-the-collector)
Your `collector-config.yaml` should look like:
```python
# collector config yaml
platform_host_url: http://localhost:8080
default_pulling_interval: 10
token: <TOKEN_FROM_STEP_1>
plugins:
  - type: mysql
    name: mysql_adapter
    database: <MYSQL_DATABASE_NAME>
    host: <MYSQL_HOST>
    port: <MYSQL_PORT>
    user: <MYSQL_USER>
    password: <MYSQL_PASSWORD>
    ssl_disabled: False # Optional, default: False
```

If you  will still have a problem, could you please share
1. demo.yaml
2. collector-cinfig.yaml
3. Logs from collector container

**Comment by DementevNikita** [comment]
Closing this as stale.
@colebagozzi please feel free to reopen, if the issue remains.
